# see https://docs.silverstripe.org/en/developer_guides/configuration/configuration/
DNADesign\Elemental\Models\BaseElement:
  extensions:
    - Kalakotra\SilverstripeElementSwitcher\Extensions\ElementalElementSwitcherExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "kalakotra/silverstripe-element-switcher:client/dist/styles/element-switcher.css"