---
Name: silverstripe-element-switcher
After: elemental
---

DNADesign\Elemental\Models\BaseElement:
  extensions:
    - Kalakotra\SilverstripeElementSwitcher\Extensions\ElementalElementSwitcherExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "kalakotra/silverstripe-element-switcher:client/dist/styles/element-switcher.css"
